language: java

env:
  - TYPE=Java
  - TYPE=JavaScript

before_install:
  - CWD=`pwd`
  - echo $CWD
  - chmod -R +rwx $CWD/scripts
  - sh $CWD/scripts/$TYPE/before_install.sh

before_script:
  - sh $CWD/scripts/$TYPE/before_script.sh

script: sudo sh $CWD/scripts/$TYPE/script.sh

after_script:
  - sh $CWD/scripts/$TYPE/after_script.sh
