language: java
before_install:
  - sudo apt-get install xvfb
  - sudo apt-get install iceweasel
  - wget -O /tmp/selenium-server-standalone-2.25.0.jar http://selenium.googlecode.com/files/selenium-server-standalone-2.25.0.jar
before_script:
  - pwd
  - export DISPLAY=:99.0
  - sudo sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99
  - java -jar /tmp/selenium-server-standalone-2.25.0.jar -port 4444 > /tmp/selenium-output.log 2> /tmp/selenium-error.log & echo $! > /tmp/selenium.pid
after_script:
  - echo "Selenium log:" 
  - cat /tmp/selenium-output.log
  - echo "Selenium error log:" 
  - cat /tmp/selenium-error.log
  - kill -9 `cat /tmp/selenium.pid`
  - sudo sh -e /etc/init.d/xvfb stop
