language: java

env:
#  - TYPE=Java
  - TYPE=JavaScript

before_install:
  - CWD=`pwd`
  - echo $CWD
  - chmod -R +x $CWD/scripts
  - $CWD/scripts/$TYPE/before_install.sh
  - export ANDROID_HOME=/tmp/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo $ANDROID_HOME

install:
  - $CWD/scripts/$TYPE/install.sh

before_script:
  - $CWD/scripts/$TYPE/before_script.sh

script:
  - $CWD/scripts/$TYPE/script.sh

after_script:
  - $CWD/scripts/$TYPE/after_script.sh
