language: java

env:
  - TYPE=Java
  - TYPE=JavaScript

before_install:
  - CWD=`pwd`
  - echo $CWD
  - chmod -R +x $CWD/scripts
  - sh $CWD/scripts/$TYPE/before_install.sh
  - export ANDROID_SDK_HOME=/tmp/android-sdk-linux
  - echo $ANDROID_SDK_HOME

before_script:
  - sh $CWD/scripts/$TYPE/before_script.sh

script:
  - sh $CWD/scripts/$TYPE/script.sh

after_script:
  - sh $CWD/scripts/$TYPE/after_script.sh
